#![no_std]
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

/*
use volatile::Volatile;
pub const ADM2         (*(volatile __near unsigned char  *)0x10)
pub const ADM2_bit     (*(volatile __near __bitf_T *)0x10)
pub const ADTYP        (((volatile __near __bitf_T *)0x10)->no0)
pub const AWC          (((volatile __near __bitf_T *)0x10)->no2)
pub const ADRCK        (((volatile __near __bitf_T *)0x10)->no3)
pub const ADUL         (*(volatile __near unsigned char  *)0x11)
pub const ADLL         (*(volatile __near unsigned char  *)0x12)
pub const ADTES        (*(volatile __near unsigned char  *)0x13)
pub const PU0          (*(volatile __near unsigned char  *)0x30)
pub const PU0_bit      (*(volatile __near __bitf_T *)0x30)
pub const PU1          (*(volatile __near unsigned char  *)0x31)
pub const PU1_bit      (*(volatile __near __bitf_T *)0x31)
pub const PU3          (*(volatile __near unsigned char  *)0x33)
pub const PU3_bit      (*(volatile __near __bitf_T *)0x33)
pub const PU4          (*(volatile __near unsigned char  *)0x34)
pub const PU4_bit      (*(volatile __near __bitf_T *)0x34)
pub const PU5          (*(volatile __near unsigned char  *)0x35)
pub const PU5_bit      (*(volatile __near __bitf_T *)0x35)
pub const PU7          (*(volatile __near unsigned char  *)0x37)
pub const PU7_bit      (*(volatile __near __bitf_T *)0x37)
pub const PU12         (*(volatile __near unsigned char  *)0x3C)
pub const PU12_bit     (*(volatile __near __bitf_T *)0x3C)
pub const PU14         (*(volatile __near unsigned char  *)0x3E)
pub const PU14_bit     (*(volatile __near __bitf_T *)0x3E)
pub const PIM0         (*(volatile __near unsigned char  *)0x40)
pub const PIM0_bit     (*(volatile __near __bitf_T *)0x40)
pub const PIM1         (*(volatile __near unsigned char  *)0x41)
pub const PIM1_bit     (*(volatile __near __bitf_T *)0x41)
pub const PIM5         (*(volatile __near unsigned char  *)0x45)
pub const PIM5_bit     (*(volatile __near __bitf_T *)0x45)
pub const POM0         (*(volatile __near unsigned char  *)0x50)
pub const POM0_bit     (*(volatile __near __bitf_T *)0x50)
pub const POM1         (*(volatile __near unsigned char  *)0x51)
pub const POM1_bit     (*(volatile __near __bitf_T *)0x51)
pub const POM5         (*(volatile __near unsigned char  *)0x55)
pub const POM5_bit     (*(volatile __near __bitf_T *)0x55)
pub const POM7         (*(volatile __near unsigned char  *)0x57)
pub const POM7_bit     (*(volatile __near __bitf_T *)0x57)
pub const PMC0         (*(volatile __near unsigned char  *)0x60)
pub const PMC0_bit     (*(volatile __near __bitf_T *)0x60)
pub const PMC12        (*(volatile __near unsigned char  *)0x6C)
pub const PMC12_bit    (*(volatile __near __bitf_T *)0x6C)
pub const PMC14        (*(volatile __near unsigned char  *)0x6E)
pub const PMC14_bit    (*(volatile __near __bitf_T *)0x6E)
pub const NFEN0        (*(volatile __near unsigned char  *)0x70)
pub const NFEN0_bit    (*(volatile __near __bitf_T *)0x70)
pub const NFEN1        (*(volatile __near unsigned char  *)0x71)
pub const NFEN1_bit    (*(volatile __near __bitf_T *)0x71)
pub const ISC          (*(volatile __near unsigned char  *)0x73)
pub const ISC_bit      (*(volatile __near __bitf_T *)0x73)
pub const TIS0         (*(volatile __near unsigned char  *)0x74)
pub const ADPC         (*(volatile __near unsigned char  *)0x76)
pub const PIOR         (*(volatile __near unsigned char  *)0x77)
pub const IAWCTL       (*(volatile __near unsigned char  *)0x78)
pub const GDIDIS       (*(volatile __near unsigned char  *)0x7D)
pub const GDIDIS_bit   (*(volatile __near __bitf_T *)0x7D)
pub const DFLCTL       (*(volatile __near unsigned char  *)0x90)
pub const DFLCTL_bit   (*(volatile __near __bitf_T *)0x90)
pub const DFLEN        (((volatile __near __bitf_T *)0x90)->no0)
pub const HIOTRM       (*(volatile __near unsigned char  *)0xA0)
pub const HOCODIV      (*(volatile __near unsigned char  *)0xA8)
pub const TEMPCAL0     (*(volatile __near unsigned char  *)0xAC)
pub const TEMPCAL1     (*(volatile __near unsigned char  *)0xAD)
pub const TEMPCAL2     (*(volatile __near unsigned char  *)0xAE)
pub const TEMPCAL3     (*(volatile __near unsigned char  *)0xAF)
pub const MDCL         (*(volatile __near unsigned short *)0xE0)
pub const MDCH         (*(volatile __near unsigned short *)0xE2)
pub const MDUC         (*(volatile __near unsigned char  *)0xE8)
pub const MDUC_bit     (*(volatile __near __bitf_T *)0xE8)
pub const DIVST        (((volatile __near __bitf_T *)0xE8)->no0)
pub const MACSF        (((volatile __near __bitf_T *)0xE8)->no1)
pub const MACOF        (((volatile __near __bitf_T *)0xE8)->no2)
pub const MDSM         (((volatile __near __bitf_T *)0xE8)->no3)
pub const MACMODE      (((volatile __near __bitf_T *)0xE8)->no6)
pub const DIVMODE      (((volatile __near __bitf_T *)0xE8)->no7)
pub const PER0         (*(volatile __near unsigned char  *)0xF0)
pub const PER0_bit     (*(volatile __near __bitf_T *)0xF0)
pub const TAU0EN       (((volatile __near __bitf_T *)0xF0)->no0)
pub const SAU0EN       (((volatile __near __bitf_T *)0xF0)->no2)
pub const SAU1EN       (((volatile __near __bitf_T *)0xF0)->no3)
pub const IICA0EN      (((volatile __near __bitf_T *)0xF0)->no4)
pub const ADCEN        (((volatile __near __bitf_T *)0xF0)->no5)
pub const RTCEN        (((volatile __near __bitf_T *)0xF0)->no7)
pub const OSMC         (*(volatile __near unsigned char  *)0xF3)
pub const RMC          (*(volatile __near unsigned char  *)0xF4)
pub const RMC_bit      (*(volatile __near __bitf_T *)0xF4)
pub const WDVOL        (((volatile __near __bitf_T *)0xF4)->no7)
pub const RPECTL       (*(volatile __near unsigned char  *)0xF5)
pub const RPECTL_bit   (*(volatile __near __bitf_T *)0xF5)
pub const RPEF         (((volatile __near __bitf_T *)0xF5)->no0)
pub const RPERDIS      (((volatile __near __bitf_T *)0xF5)->no7)
pub const BCDADJ       (*(volatile __near unsigned char  *)0xFE)
pub const SSR00        (*(volatile __near unsigned short *)0x100)
pub const SSR00L       (*(volatile __near unsigned char  *)0x100)
pub const SSR01        (*(volatile __near unsigned short *)0x102)
pub const SSR01L       (*(volatile __near unsigned char  *)0x102)
pub const SSR02        (*(volatile __near unsigned short *)0x104)
pub const SSR02L       (*(volatile __near unsigned char  *)0x104)
pub const SSR03        (*(volatile __near unsigned short *)0x106)
pub const SSR03L       (*(volatile __near unsigned char  *)0x106)
pub const SIR00        (*(volatile __near unsigned short *)0x108)
pub const SIR00L       (*(volatile __near unsigned char  *)0x108)
pub const SIR01        (*(volatile __near unsigned short *)0x10A)
pub const SIR01L       (*(volatile __near unsigned char  *)0x10A)
pub const SIR02        (*(volatile __near unsigned short *)0x10C)
pub const SIR02L       (*(volatile __near unsigned char  *)0x10C)
pub const SIR03        (*(volatile __near unsigned short *)0x10E)
pub const SIR03L       (*(volatile __near unsigned char  *)0x10E)
pub const SMR00        (*(volatile __near unsigned short *)0x110)
pub const SMR01        (*(volatile __near unsigned short *)0x112)
pub const SMR02        (*(volatile __near unsigned short *)0x114)
pub const SMR03        (*(volatile __near unsigned short *)0x116)
pub const SCR00        (*(volatile __near unsigned short *)0x118)
pub const SCR01        (*(volatile __near unsigned short *)0x11A)
pub const SCR02        (*(volatile __near unsigned short *)0x11C)
pub const SCR03        (*(volatile __near unsigned short *)0x11E)
pub const SE0          (*(volatile __near unsigned short *)0x120)
pub const SE0L         (*(volatile __near unsigned char  *)0x120)
pub const SE0L_bit     (*(volatile __near __bitf_T *)0x120)
pub const SS0          (*(volatile __near unsigned short *)0x122)
pub const SS0L         (*(volatile __near unsigned char  *)0x122)
pub const SS0L_bit     (*(volatile __near __bitf_T *)0x122)
pub const ST0          (*(volatile __near unsigned short *)0x124)
pub const ST0L         (*(volatile __near unsigned char  *)0x124)
pub const ST0L_bit     (*(volatile __near __bitf_T *)0x124)
pub const SPS0         (*(volatile __near unsigned short *)0x126)
pub const SPS0L        (*(volatile __near unsigned char  *)0x126)
pub const SO0          (*(volatile __near unsigned short *)0x128)
pub const SOE0         (*(volatile __near unsigned short *)0x12A)
pub const SOE0L        (*(volatile __near unsigned char  *)0x12A)
pub const SOE0L_bit    (*(volatile __near __bitf_T *)0x12A)
pub const SOL0         (*(volatile __near unsigned short *)0x134)
pub const SOL0L        (*(volatile __near unsigned char  *)0x134)
pub const SSC0         (*(volatile __near unsigned short *)0x138)
pub const SSC0L        (*(volatile __near unsigned char  *)0x138)
pub const SSR10        (*(volatile __near unsigned short *)0x140)
pub const SSR10L       (*(volatile __near unsigned char  *)0x140)
pub const SSR11        (*(volatile __near unsigned short *)0x142)
pub const SSR11L       (*(volatile __near unsigned char  *)0x142)
pub const SIR10        (*(volatile __near unsigned short *)0x148)
pub const SIR10L       (*(volatile __near unsigned char  *)0x148)
pub const SIR11        (*(volatile __near unsigned short *)0x14A)
pub const SIR11L       (*(volatile __near unsigned char  *)0x14A)
pub const SMR10        (*(volatile __near unsigned short *)0x150)
pub const SMR11        (*(volatile __near unsigned short *)0x152)
pub const SCR10        (*(volatile __near unsigned short *)0x158)
pub const SCR11        (*(volatile __near unsigned short *)0x15A)
pub const SE1          (*(volatile __near unsigned short *)0x160)
pub const SE1L         (*(volatile __near unsigned char  *)0x160)
pub const SE1L_bit     (*(volatile __near __bitf_T *)0x160)
pub const SS1          (*(volatile __near unsigned short *)0x162)
pub const SS1L         (*(volatile __near unsigned char  *)0x162)
pub const SS1L_bit     (*(volatile __near __bitf_T *)0x162)
pub const ST1          (*(volatile __near unsigned short *)0x164)
pub const ST1L         (*(volatile __near unsigned char  *)0x164)
pub const ST1L_bit     (*(volatile __near __bitf_T *)0x164)
pub const SPS1         (*(volatile __near unsigned short *)0x166)
pub const SPS1L        (*(volatile __near unsigned char  *)0x166)
pub const SO1          (*(volatile __near unsigned short *)0x168)
pub const SOE1         (*(volatile __near unsigned short *)0x16A)
pub const SOE1L        (*(volatile __near unsigned char  *)0x16A)
pub const SOE1L_bit    (*(volatile __near __bitf_T *)0x16A)
pub const SOL1         (*(volatile __near unsigned short *)0x174)
pub const SOL1L        (*(volatile __near unsigned char  *)0x174)
pub const TCR00        (*(volatile __near unsigned short *)0x180)
pub const TCR01        (*(volatile __near unsigned short *)0x182)
pub const TCR02        (*(volatile __near unsigned short *)0x184)
pub const TCR03        (*(volatile __near unsigned short *)0x186)
pub const TCR04        (*(volatile __near unsigned short *)0x188)
pub const TCR05        (*(volatile __near unsigned short *)0x18A)
pub const TCR06        (*(volatile __near unsigned short *)0x18C)
pub const TCR07        (*(volatile __near unsigned short *)0x18E)
pub const TMR00        (*(volatile __near unsigned short *)0x190)
pub const TMR01        (*(volatile __near unsigned short *)0x192)
pub const TMR02        (*(volatile __near unsigned short *)0x194)
pub const TMR03        (*(volatile __near unsigned short *)0x196)
pub const TMR04        (*(volatile __near unsigned short *)0x198)
pub const TMR05        (*(volatile __near unsigned short *)0x19A)
pub const TMR06        (*(volatile __near unsigned short *)0x19C)
pub const TMR07        (*(volatile __near unsigned short *)0x19E)
pub const TSR00        (*(volatile __near unsigned short *)0x1A0)
pub const TSR00L       (*(volatile __near unsigned char  *)0x1A0)
pub const TSR01        (*(volatile __near unsigned short *)0x1A2)
pub const TSR01L       (*(volatile __near unsigned char  *)0x1A2)
pub const TSR02        (*(volatile __near unsigned short *)0x1A4)
pub const TSR02L       (*(volatile __near unsigned char  *)0x1A4)
pub const TSR03        (*(volatile __near unsigned short *)0x1A6)
pub const TSR03L       (*(volatile __near unsigned char  *)0x1A6)
pub const TSR04        (*(volatile __near unsigned short *)0x1A8)
pub const TSR04L       (*(volatile __near unsigned char  *)0x1A8)
pub const TSR05        (*(volatile __near unsigned short *)0x1AA)
pub const TSR05L       (*(volatile __near unsigned char  *)0x1AA)
pub const TSR06        (*(volatile __near unsigned short *)0x1AC)
pub const TSR06L       (*(volatile __near unsigned char  *)0x1AC)
pub const TSR07        (*(volatile __near unsigned short *)0x1AE)
pub const TSR07L       (*(volatile __near unsigned char  *)0x1AE)
pub const TE0          (*(volatile __near unsigned short *)0x1B0)
pub const TE0L         (*(volatile __near unsigned char  *)0x1B0)
pub const TE0L_bit     (*(volatile __near __bitf_T *)0x1B0)
pub const TS0          (*(volatile __near unsigned short *)0x1B2)
pub const TS0L         (*(volatile __near unsigned char  *)0x1B2)
pub const TS0L_bit     (*(volatile __near __bitf_T *)0x1B2)
pub const TT0          (*(volatile __near unsigned short *)0x1B4)
pub const TT0L         (*(volatile __near unsigned char  *)0x1B4)
pub const TT0L_bit     (*(volatile __near __bitf_T *)0x1B4)
pub const TPS0         (*(volatile __near unsigned short *)0x1B6)
pub const TO0          (*(volatile __near unsigned short *)0x1B8)
pub const TO0L         (*(volatile __near unsigned char  *)0x1B8)
pub const TOE0         (*(volatile __near unsigned short *)0x1BA)
pub const TOE0L        (*(volatile __near unsigned char  *)0x1BA)
pub const TOE0L_bit    (*(volatile __near __bitf_T *)0x1BA)
pub const TOL0         (*(volatile __near unsigned short *)0x1BC)
pub const TOL0L        (*(volatile __near unsigned char  *)0x1BC)
pub const TOM0         (*(volatile __near unsigned short *)0x1BE)
pub const TOM0L        (*(volatile __near unsigned char  *)0x1BE)
pub const IICCTL00     (*(volatile __near unsigned char  *)0x230)
pub const IICCTL00_bit (*(volatile __near __bitf_T *)0x230)
pub const SPT0         (((volatile __near __bitf_T *)0x230)->no0)
pub const STT0         (((volatile __near __bitf_T *)0x230)->no1)
pub const ACKE0        (((volatile __near __bitf_T *)0x230)->no2)
pub const WTIM0        (((volatile __near __bitf_T *)0x230)->no3)
pub const SPIE0        (((volatile __near __bitf_T *)0x230)->no4)
pub const WREL0        (((volatile __near __bitf_T *)0x230)->no5)
pub const LREL0        (((volatile __near __bitf_T *)0x230)->no6)
pub const IICE0        (((volatile __near __bitf_T *)0x230)->no7)
pub const IICCTL01     (*(volatile __near unsigned char  *)0x231)
pub const IICCTL01_bit (*(volatile __near __bitf_T *)0x231)
pub const PRS0         (((volatile __near __bitf_T *)0x231)->no0)
pub const DFC0         (((volatile __near __bitf_T *)0x231)->no2)
pub const SMC0         (((volatile __near __bitf_T *)0x231)->no3)
pub const DAD0         (((volatile __near __bitf_T *)0x231)->no4)
pub const CLD0         (((volatile __near __bitf_T *)0x231)->no5)
pub const WUP0         (((volatile __near __bitf_T *)0x231)->no7)
pub const IICWL0       (*(volatile __near unsigned char  *)0x232)
pub const IICWH0       (*(volatile __near unsigned char  *)0x233)
pub const SVA0         (*(volatile __near unsigned char  *)0x234)
pub const CRC0CTL      (*(volatile __near unsigned char  *)0x2F0)
pub const CRC0CTL_bit  (*(volatile __near __bitf_T *)0x2F0)
pub const CRC0EN       (((volatile __near __bitf_T *)0x2F0)->no7)
pub const PGCRCL       (*(volatile __near unsigned short *)0x2F2)
pub const CRCD         (*(volatile __near unsigned short *)0x2FA)
pub const P0           (*(volatile __near unsigned char  *)0xFF00)
pub const P0_bit       (*(volatile __near __bitf_T *)0xFF00)
pub const P1           (*(volatile __near unsigned char  *)0xFF01)
pub const P1_bit       (*(volatile __near __bitf_T *)0xFF01)
pub const P2           (*(volatile __near unsigned char  *)0xFF02)
pub const P2_bit       (*(volatile __near __bitf_T *)0xFF02)
pub const P3           (*(volatile __near unsigned char  *)0xFF03)
pub const P3_bit       (*(volatile __near __bitf_T *)0xFF03)
pub const P4           (*(volatile __near unsigned char  *)0xFF04)
pub const P4_bit       (*(volatile __near __bitf_T *)0xFF04)
pub const P5           (*(volatile __near unsigned char  *)0xFF05)
pub const P5_bit       (*(volatile __near __bitf_T *)0xFF05)
pub const P6           (*(volatile __near unsigned char  *)0xFF06)
pub const P6_bit       (*(volatile __near __bitf_T *)0xFF06)
pub const P7           (*(volatile __near unsigned char  *)0xFF07)
pub const P7_bit       (*(volatile __near __bitf_T *)0xFF07)
pub const P12          (*(volatile __near unsigned char  *)0xFF0C)
pub const P12_bit      (*(volatile __near __bitf_T *)0xFF0C)
pub const P13          (*(volatile __near unsigned char  *)0xFF0D)
pub const P13_bit      (*(volatile __near __bitf_T *)0xFF0D)
pub const P14          (*(volatile __near unsigned char  *)0xFF0E)
pub const P14_bit      (*(volatile __near __bitf_T *)0xFF0E)
pub const SDR00        (*(volatile __near unsigned short *)0xFF10)
pub const SIO00        (*(volatile __near unsigned char  *)0xFF10)
pub const TXD0         (*(volatile __near unsigned char  *)0xFF10)
pub const SDR01        (*(volatile __near unsigned short *)0xFF12)
pub const RXD0         (*(volatile __near unsigned char  *)0xFF12)
pub const SIO01        (*(volatile __near unsigned char  *)0xFF12)
pub const TDR00        (*(volatile __near unsigned short *)0xFF18)
pub const TDR01        (*(volatile __near unsigned short *)0xFF1A)
pub const TDR01L       (*(volatile __near unsigned char  *)0xFF1A)
pub const TDR01H       (*(volatile __near unsigned char  *)0xFF1B)
pub const ADCR         (*(volatile __near unsigned short *)0xFF1E)
pub const ADCRH        (*(volatile __near unsigned char  *)0xFF1F)
pub const PM0          (*(volatile __near unsigned char  *)0xFF20)
pub const PM0_bit      (*(volatile __near __bitf_T *)0xFF20)
pub const PM1          (*(volatile __near unsigned char  *)0xFF21)
pub const PM1_bit      (*(volatile __near __bitf_T *)0xFF21)
pub const PM2          (*(volatile __near unsigned char  *)0xFF22)
pub const PM2_bit      (*(volatile __near __bitf_T *)0xFF22)
pub const PM3          (*(volatile __near unsigned char  *)0xFF23)
pub const PM3_bit      (*(volatile __near __bitf_T *)0xFF23)
pub const PM4          (*(volatile __near unsigned char  *)0xFF24)
pub const PM4_bit      (*(volatile __near __bitf_T *)0xFF24)
pub const PM5          (*(volatile __near unsigned char  *)0xFF25)
pub const PM5_bit      (*(volatile __near __bitf_T *)0xFF25)
pub const PM6          (*(volatile __near unsigned char  *)0xFF26)
pub const PM6_bit      (*(volatile __near __bitf_T *)0xFF26)
pub const PM7          (*(volatile __near unsigned char  *)0xFF27)
pub const PM7_bit      (*(volatile __near __bitf_T *)0xFF27)
pub const PM12         (*(volatile __near unsigned char  *)0xFF2C)
pub const PM12_bit     (*(volatile __near __bitf_T *)0xFF2C)
pub const PM14         (*(volatile __near unsigned char  *)0xFF2E)
pub const PM14_bit     (*(volatile __near __bitf_T *)0xFF2E)
pub const ADM0         (*(volatile __near unsigned char  *)0xFF30)
pub const ADM0_bit     (*(volatile __near __bitf_T *)0xFF30)
pub const ADCE         (((volatile __near __bitf_T *)0xFF30)->no0)
pub const ADCS         (((volatile __near __bitf_T *)0xFF30)->no7)
pub const ADS          (*(volatile __near unsigned char  *)0xFF31)
pub const ADS_bit      (*(volatile __near __bitf_T *)0xFF31)
pub const ADM1         (*(volatile __near unsigned char  *)0xFF32)
pub const ADM1_bit     (*(volatile __near __bitf_T *)0xFF32)
pub const KRM          (*(volatile __near unsigned char  *)0xFF37)
pub const KRM_bit      (*(volatile __near __bitf_T *)0xFF37)
pub const EGP0         (*(volatile __near unsigned char  *)0xFF38)
pub const EGP0_bit     (*(volatile __near __bitf_T *)0xFF38)
pub const EGN0         (*(volatile __near unsigned char  *)0xFF39)
pub const EGN0_bit     (*(volatile __near __bitf_T *)0xFF39)
pub const EGP1         (*(volatile __near unsigned char  *)0xFF3A)
pub const EGP1_bit     (*(volatile __near __bitf_T *)0xFF3A)
pub const EGN1         (*(volatile __near unsigned char  *)0xFF3B)
pub const EGN1_bit     (*(volatile __near __bitf_T *)0xFF3B)
pub const SDR02        (*(volatile __near unsigned short *)0xFF44)
pub const SIO10        (*(volatile __near unsigned char  *)0xFF44)
pub const TXD1         (*(volatile __near unsigned char  *)0xFF44)
pub const SDR03        (*(volatile __near unsigned short *)0xFF46)
pub const RXD1         (*(volatile __near unsigned char  *)0xFF46)
pub const SIO11        (*(volatile __near unsigned char  *)0xFF46)
pub const SDR10        (*(volatile __near unsigned short *)0xFF48)
pub const SIO20        (*(volatile __near unsigned char  *)0xFF48)
pub const TXD2         (*(volatile __near unsigned char  *)0xFF48)
pub const SDR11        (*(volatile __near unsigned short *)0xFF4A)
pub const RXD2         (*(volatile __near unsigned char  *)0xFF4A)
pub const SIO21        (*(volatile __near unsigned char  *)0xFF4A)
pub const IICA0        (*(volatile __near unsigned char  *)0xFF50)
pub const IICS0        (*(volatile __near unsigned char  *)0xFF51)
pub const IICS0_bit    (*(volatile __near __bitf_T *)0xFF51)
pub const SPD0         (((volatile __near __bitf_T *)0xFF51)->no0)
pub const STD0         (((volatile __near __bitf_T *)0xFF51)->no1)
pub const ACKD0        (((volatile __near __bitf_T *)0xFF51)->no2)
pub const TRC0         (((volatile __near __bitf_T *)0xFF51)->no3)
pub const COI0         (((volatile __near __bitf_T *)0xFF51)->no4)
pub const EXC0         (((volatile __near __bitf_T *)0xFF51)->no5)
pub const ALD0         (((volatile __near __bitf_T *)0xFF51)->no6)
pub const MSTS0        (((volatile __near __bitf_T *)0xFF51)->no7)
pub const IICF0        (*(volatile __near unsigned char  *)0xFF52)
pub const IICF0_bit    (*(volatile __near __bitf_T *)0xFF52)
pub const IICRSV0      (((volatile __near __bitf_T *)0xFF52)->no0)
pub const STCEN0       (((volatile __near __bitf_T *)0xFF52)->no1)
pub const IICBSY0      (((volatile __near __bitf_T *)0xFF52)->no6)
pub const STCF0        (((volatile __near __bitf_T *)0xFF52)->no7)
pub const TDR02        (*(volatile __near unsigned short *)0xFF64)
pub const TDR03        (*(volatile __near unsigned short *)0xFF66)
pub const TDR03L       (*(volatile __near unsigned char  *)0xFF66)
pub const TDR03H       (*(volatile __near unsigned char  *)0xFF67)
pub const TDR04        (*(volatile __near unsigned short *)0xFF68)
pub const TDR05        (*(volatile __near unsigned short *)0xFF6A)
pub const TDR06        (*(volatile __near unsigned short *)0xFF6C)
pub const TDR07        (*(volatile __near unsigned short *)0xFF6E)
pub const ITMC         (*(volatile __near unsigned short *)0xFF90)
pub const SEC          (*(volatile __near unsigned char  *)0xFF92)
pub const MIN          (*(volatile __near unsigned char  *)0xFF93)
pub const HOUR         (*(volatile __near unsigned char  *)0xFF94)
pub const WEEK         (*(volatile __near unsigned char  *)0xFF95)
pub const DAY          (*(volatile __near unsigned char  *)0xFF96)
pub const MONTH        (*(volatile __near unsigned char  *)0xFF97)
pub const YEAR         (*(volatile __near unsigned char  *)0xFF98)
pub const SUBCUD       (*(volatile __near unsigned char  *)0xFF99)
pub const ALARMWM      (*(volatile __near unsigned char  *)0xFF9A)
pub const ALARMWH      (*(volatile __near unsigned char  *)0xFF9B)
pub const ALARMWW      (*(volatile __near unsigned char  *)0xFF9C)
pub const RTCC0        (*(volatile __near unsigned char  *)0xFF9D)
pub const RTCC0_bit    (*(volatile __near __bitf_T *)0xFF9D)
pub const RCLOE1       (((volatile __near __bitf_T *)0xFF9D)->no5)
pub const RTCE         (((volatile __near __bitf_T *)0xFF9D)->no7)
pub const RTCC1        (*(volatile __near unsigned char  *)0xFF9E)
pub const RTCC1_bit    (*(volatile __near __bitf_T *)0xFF9E)
pub const RWAIT        (((volatile __near __bitf_T *)0xFF9E)->no0)
pub const RWST         (((volatile __near __bitf_T *)0xFF9E)->no1)
pub const RIFG         (((volatile __near __bitf_T *)0xFF9E)->no3)
pub const WAFG         (((volatile __near __bitf_T *)0xFF9E)->no4)
pub const WALIE        (((volatile __near __bitf_T *)0xFF9E)->no6)
pub const WALE         (((volatile __near __bitf_T *)0xFF9E)->no7)
pub const CMC          (*(volatile __near unsigned char  *)0xFFA0)
pub const CSC          (*(volatile __near unsigned char  *)0xFFA1)
pub const CSC_bit      (*(volatile __near __bitf_T *)0xFFA1)
pub const HIOSTOP      (((volatile __near __bitf_T *)0xFFA1)->no0)
pub const XTSTOP       (((volatile __near __bitf_T *)0xFFA1)->no6)
pub const MSTOP        (((volatile __near __bitf_T *)0xFFA1)->no7)
pub const OSTC         (*(volatile __near unsigned char  *)0xFFA2)
pub const OSTC_bit     (*(volatile __near __bitf_T *)0xFFA2)
pub const OSTS         (*(volatile __near unsigned char  *)0xFFA3)
pub const CKC          (*(volatile __near unsigned char  *)0xFFA4)
pub const CKC_bit      (*(volatile __near __bitf_T *)0xFFA4)
pub const SDIV         (((volatile __near __bitf_T *)0xFFA4)->no3)
pub const MCM0         (((volatile __near __bitf_T *)0xFFA4)->no4)
pub const MCS          (((volatile __near __bitf_T *)0xFFA4)->no5)
pub const CSS          (((volatile __near __bitf_T *)0xFFA4)->no6)
pub const CLS          (((volatile __near __bitf_T *)0xFFA4)->no7)
pub const CKS0         (*(volatile __near unsigned char  *)0xFFA5)
pub const CKS0_bit     (*(volatile __near __bitf_T *)0xFFA5)
pub const PCLOE0       (((volatile __near __bitf_T *)0xFFA5)->no7)
pub const CKS1         (*(volatile __near unsigned char  *)0xFFA6)
pub const CKS1_bit     (*(volatile __near __bitf_T *)0xFFA6)
pub const PCLOE1       (((volatile __near __bitf_T *)0xFFA6)->no7)
pub const RESF         (*(volatile __near unsigned char  *)0xFFA8)
pub const LVIM         (*(volatile __near unsigned char  *)0xFFA9)
pub const LVIM_bit     (*(volatile __near __bitf_T *)0xFFA9)
pub const LVIF         (((volatile __near __bitf_T *)0xFFA9)->no0)
pub const LVIOMSK      (((volatile __near __bitf_T *)0xFFA9)->no1)
pub const LVISEN       (((volatile __near __bitf_T *)0xFFA9)->no7)
pub const LVIS         (*(volatile __near unsigned char  *)0xFFAA)
pub const LVIS_bit     (*(volatile __near __bitf_T *)0xFFAA)
pub const LVILV        (((volatile __near __bitf_T *)0xFFAA)->no0)
pub const LVIMD        (((volatile __near __bitf_T *)0xFFAA)->no7)
pub const WDTE         (*(volatile __near unsigned char  *)0xFFAB)
pub const CRCIN        (*(volatile __near unsigned char  *)0xFFAC)
pub const DSA0         (*(volatile __near unsigned char  *)0xFFB0)
pub const DSA1         (*(volatile __near unsigned char  *)0xFFB1)
pub const DRA0         (*(volatile __near unsigned short *)0xFFB2)
pub const DRA0L        (*(volatile __near unsigned char  *)0xFFB2)
pub const DRA0H        (*(volatile __near unsigned char  *)0xFFB3)
pub const DRA1         (*(volatile __near unsigned short *)0xFFB4)
pub const DRA1L        (*(volatile __near unsigned char  *)0xFFB4)
pub const DRA1H        (*(volatile __near unsigned char  *)0xFFB5)
pub const DBC0         (*(volatile __near unsigned short *)0xFFB6)
pub const DBC0L        (*(volatile __near unsigned char  *)0xFFB6)
pub const DBC0H        (*(volatile __near unsigned char  *)0xFFB7)
pub const DBC1         (*(volatile __near unsigned short *)0xFFB8)
pub const DBC1L        (*(volatile __near unsigned char  *)0xFFB8)
pub const DBC1H        (*(volatile __near unsigned char  *)0xFFB9)
pub const DMC0         (*(volatile __near unsigned char  *)0xFFBA)
pub const DMC0_bit     (*(volatile __near __bitf_T *)0xFFBA)
pub const DWAIT0       (((volatile __near __bitf_T *)0xFFBA)->no4)
pub const DS0          (((volatile __near __bitf_T *)0xFFBA)->no5)
pub const DRS0         (((volatile __near __bitf_T *)0xFFBA)->no6)
pub const STG0         (((volatile __near __bitf_T *)0xFFBA)->no7)
pub const DMC1         (*(volatile __near unsigned char  *)0xFFBB)
pub const DMC1_bit     (*(volatile __near __bitf_T *)0xFFBB)
pub const DWAIT1       (((volatile __near __bitf_T *)0xFFBB)->no4)
pub const DS1          (((volatile __near __bitf_T *)0xFFBB)->no5)
pub const DRS1         (((volatile __near __bitf_T *)0xFFBB)->no6)
pub const STG1         (((volatile __near __bitf_T *)0xFFBB)->no7)
pub const DRC0         (*(volatile __near unsigned char  *)0xFFBC)
pub const DRC0_bit     (*(volatile __near __bitf_T *)0xFFBC)
pub const DST0         (((volatile __near __bitf_T *)0xFFBC)->no0)
pub const DEN0         (((volatile __near __bitf_T *)0xFFBC)->no7)
pub const DRC1         (*(volatile __near unsigned char  *)0xFFBD)
pub const DRC1_bit     (*(volatile __near __bitf_T *)0xFFBD)
pub const DST1         (((volatile __near __bitf_T *)0xFFBD)->no0)
pub const DEN1         (((volatile __near __bitf_T *)0xFFBD)->no7)
pub const IF2          (*(volatile __near unsigned short *)0xFFD0)
pub const IF2L         (*(volatile __near unsigned char  *)0xFFD0)
pub const IF2L_bit     (*(volatile __near __bitf_T *)0xFFD0)
pub const IF2H         (*(volatile __near unsigned char  *)0xFFD1)
pub const IF2H_bit     (*(volatile __near __bitf_T *)0xFFD1)
pub const TMIF05       (((volatile __near __bitf_T *)0xFFD0)->no0)
pub const TMIF06       (((volatile __near __bitf_T *)0xFFD0)->no1)
pub const TMIF07       (((volatile __near __bitf_T *)0xFFD0)->no2)
pub const PIF6         (((volatile __near __bitf_T *)0xFFD0)->no3)
pub const PIF7         (((volatile __near __bitf_T *)0xFFD0)->no4)
pub const PIF8         (((volatile __near __bitf_T *)0xFFD0)->no5)
pub const PIF9         (((volatile __near __bitf_T *)0xFFD0)->no6)
pub const PIF10        (((volatile __near __bitf_T *)0xFFD0)->no7)
pub const PIF11        (((volatile __near __bitf_T *)0xFFD1)->no0)
pub const MDIF         (((volatile __near __bitf_T *)0xFFD1)->no5)
pub const FLIF         (((volatile __near __bitf_T *)0xFFD1)->no7)
pub const MK2          (*(volatile __near unsigned short *)0xFFD4)
pub const MK2L         (*(volatile __near unsigned char  *)0xFFD4)
pub const MK2L_bit     (*(volatile __near __bitf_T *)0xFFD4)
pub const MK2H         (*(volatile __near unsigned char  *)0xFFD5)
pub const MK2H_bit     (*(volatile __near __bitf_T *)0xFFD5)
pub const TMMK05       (((volatile __near __bitf_T *)0xFFD4)->no0)
pub const TMMK06       (((volatile __near __bitf_T *)0xFFD4)->no1)
pub const TMMK07       (((volatile __near __bitf_T *)0xFFD4)->no2)
pub const PMK6         (((volatile __near __bitf_T *)0xFFD4)->no3)
pub const PMK7         (((volatile __near __bitf_T *)0xFFD4)->no4)
pub const PMK8         (((volatile __near __bitf_T *)0xFFD4)->no5)
pub const PMK9         (((volatile __near __bitf_T *)0xFFD4)->no6)
pub const PMK10        (((volatile __near __bitf_T *)0xFFD4)->no7)
pub const PMK11        (((volatile __near __bitf_T *)0xFFD5)->no0)
pub const MDMK         (((volatile __near __bitf_T *)0xFFD5)->no5)
pub const FLMK         (((volatile __near __bitf_T *)0xFFD5)->no7)
pub const PR02         (*(volatile __near unsigned short *)0xFFD8)
pub const PR02L        (*(volatile __near unsigned char  *)0xFFD8)
pub const PR02L_bit    (*(volatile __near __bitf_T *)0xFFD8)
pub const PR02H        (*(volatile __near unsigned char  *)0xFFD9)
pub const PR02H_bit    (*(volatile __near __bitf_T *)0xFFD9)
pub const TMPR005      (((volatile __near __bitf_T *)0xFFD8)->no0)
pub const TMPR006      (((volatile __near __bitf_T *)0xFFD8)->no1)
pub const TMPR007      (((volatile __near __bitf_T *)0xFFD8)->no2)
pub const PPR06        (((volatile __near __bitf_T *)0xFFD8)->no3)
pub const PPR07        (((volatile __near __bitf_T *)0xFFD8)->no4)
pub const PPR08        (((volatile __near __bitf_T *)0xFFD8)->no5)
pub const PPR09        (((volatile __near __bitf_T *)0xFFD8)->no6)
pub const PPR010       (((volatile __near __bitf_T *)0xFFD8)->no7)
pub const PPR011       (((volatile __near __bitf_T *)0xFFD9)->no0)
pub const MDPR0        (((volatile __near __bitf_T *)0xFFD9)->no5)
pub const FLPR0        (((volatile __near __bitf_T *)0xFFD9)->no7)
pub const PR12         (*(volatile __near unsigned short *)0xFFDC)
pub const PR12L        (*(volatile __near unsigned char  *)0xFFDC)
pub const PR12L_bit    (*(volatile __near __bitf_T *)0xFFDC)
pub const PR12H        (*(volatile __near unsigned char  *)0xFFDD)
pub const PR12H_bit    (*(volatile __near __bitf_T *)0xFFDD)
pub const TMPR105      (((volatile __near __bitf_T *)0xFFDC)->no0)
pub const TMPR106      (((volatile __near __bitf_T *)0xFFDC)->no1)
pub const TMPR107      (((volatile __near __bitf_T *)0xFFDC)->no2)
pub const PPR16        (((volatile __near __bitf_T *)0xFFDC)->no3)
pub const PPR17        (((volatile __near __bitf_T *)0xFFDC)->no4)
pub const PPR18        (((volatile __near __bitf_T *)0xFFDC)->no5)
pub const PPR19        (((volatile __near __bitf_T *)0xFFDC)->no6)
pub const PPR110       (((volatile __near __bitf_T *)0xFFDC)->no7)
pub const PPR111       (((volatile __near __bitf_T *)0xFFDD)->no0)
pub const MDPR1        (((volatile __near __bitf_T *)0xFFDD)->no5)
pub const FLPR1        (((volatile __near __bitf_T *)0xFFDD)->no7)
pub const IF0          (*(volatile __near unsigned short *)0xFFE0)
pub const IF0L         (*(volatile __near unsigned char  *)0xFFE0)
pub const IF0L_bit     (*(volatile __near __bitf_T *)0xFFE0)
pub const IF0H         (*(volatile __near unsigned char  *)0xFFE1)
pub const IF0H_bit     (*(volatile __near __bitf_T *)0xFFE1)
pub const WDTIIF       (((volatile __near __bitf_T *)0xFFE0)->no0)
pub const LVIIF        (((volatile __near __bitf_T *)0xFFE0)->no1)
pub const PIF0         (((volatile __near __bitf_T *)0xFFE0)->no2)
pub const PIF1         (((volatile __near __bitf_T *)0xFFE0)->no3)
pub const PIF2         (((volatile __near __bitf_T *)0xFFE0)->no4)
pub const PIF3         (((volatile __near __bitf_T *)0xFFE0)->no5)
pub const PIF4         (((volatile __near __bitf_T *)0xFFE0)->no6)
pub const PIF5         (((volatile __near __bitf_T *)0xFFE0)->no7)
pub const CSIIF20      (((volatile __near __bitf_T *)0xFFE1)->no0)
pub const IICIF20      (((volatile __near __bitf_T *)0xFFE1)->no0)
pub const STIF2        (((volatile __near __bitf_T *)0xFFE1)->no0)
pub const CSIIF21      (((volatile __near __bitf_T *)0xFFE1)->no1)
pub const IICIF21      (((volatile __near __bitf_T *)0xFFE1)->no1)
pub const SRIF2        (((volatile __near __bitf_T *)0xFFE1)->no1)
pub const SREIF2       (((volatile __near __bitf_T *)0xFFE1)->no2)
pub const DMAIF0       (((volatile __near __bitf_T *)0xFFE1)->no3)
pub const DMAIF1       (((volatile __near __bitf_T *)0xFFE1)->no4)
pub const CSIIF00      (((volatile __near __bitf_T *)0xFFE1)->no5)
pub const IICIF00      (((volatile __near __bitf_T *)0xFFE1)->no5)
pub const STIF0        (((volatile __near __bitf_T *)0xFFE1)->no5)
pub const CSIIF01      (((volatile __near __bitf_T *)0xFFE1)->no6)
pub const IICIF01      (((volatile __near __bitf_T *)0xFFE1)->no6)
pub const SRIF0        (((volatile __near __bitf_T *)0xFFE1)->no6)
pub const SREIF0       (((volatile __near __bitf_T *)0xFFE1)->no7)
pub const TMIF01H      (((volatile __near __bitf_T *)0xFFE1)->no7)
pub const IF1          (*(volatile __near unsigned short *)0xFFE2)
pub const IF1L         (*(volatile __near unsigned char  *)0xFFE2)
pub const IF1L_bit     (*(volatile __near __bitf_T *)0xFFE2)
pub const IF1H         (*(volatile __near unsigned char  *)0xFFE3)
pub const IF1H_bit     (*(volatile __near __bitf_T *)0xFFE3)
pub const CSIIF10      (((volatile __near __bitf_T *)0xFFE2)->no0)
pub const IICIF10      (((volatile __near __bitf_T *)0xFFE2)->no0)
pub const STIF1        (((volatile __near __bitf_T *)0xFFE2)->no0)
pub const CSIIF11      (((volatile __near __bitf_T *)0xFFE2)->no1)
pub const IICIF11      (((volatile __near __bitf_T *)0xFFE2)->no1)
pub const SRIF1        (((volatile __near __bitf_T *)0xFFE2)->no1)
pub const SREIF1       (((volatile __near __bitf_T *)0xFFE2)->no2)
pub const TMIF03H      (((volatile __near __bitf_T *)0xFFE2)->no2)
pub const IICAIF0      (((volatile __near __bitf_T *)0xFFE2)->no3)
pub const TMIF00       (((volatile __near __bitf_T *)0xFFE2)->no4)
pub const TMIF01       (((volatile __near __bitf_T *)0xFFE2)->no5)
pub const TMIF02       (((volatile __near __bitf_T *)0xFFE2)->no6)
pub const TMIF03       (((volatile __near __bitf_T *)0xFFE2)->no7)
pub const ADIF         (((volatile __near __bitf_T *)0xFFE3)->no0)
pub const RTCIF        (((volatile __near __bitf_T *)0xFFE3)->no1)
pub const ITIF         (((volatile __near __bitf_T *)0xFFE3)->no2)
pub const KRIF         (((volatile __near __bitf_T *)0xFFE3)->no3)
pub const TMIF04       (((volatile __near __bitf_T *)0xFFE3)->no7)
pub const MK0          (*(volatile __near unsigned short *)0xFFE4)
pub const MK0L         (*(volatile __near unsigned char  *)0xFFE4)
pub const MK0L_bit     (*(volatile __near __bitf_T *)0xFFE4)
pub const MK0H         (*(volatile __near unsigned char  *)0xFFE5)
pub const MK0H_bit     (*(volatile __near __bitf_T *)0xFFE5)
pub const WDTIMK       (((volatile __near __bitf_T *)0xFFE4)->no0)
pub const LVIMK        (((volatile __near __bitf_T *)0xFFE4)->no1)
pub const PMK0         (((volatile __near __bitf_T *)0xFFE4)->no2)
pub const PMK1         (((volatile __near __bitf_T *)0xFFE4)->no3)
pub const PMK2         (((volatile __near __bitf_T *)0xFFE4)->no4)
pub const PMK3         (((volatile __near __bitf_T *)0xFFE4)->no5)
pub const PMK4         (((volatile __near __bitf_T *)0xFFE4)->no6)
pub const PMK5         (((volatile __near __bitf_T *)0xFFE4)->no7)
pub const CSIMK20      (((volatile __near __bitf_T *)0xFFE5)->no0)
pub const IICMK20      (((volatile __near __bitf_T *)0xFFE5)->no0)
pub const STMK2        (((volatile __near __bitf_T *)0xFFE5)->no0)
pub const CSIMK21      (((volatile __near __bitf_T *)0xFFE5)->no1)
pub const IICMK21      (((volatile __near __bitf_T *)0xFFE5)->no1)
pub const SRMK2        (((volatile __near __bitf_T *)0xFFE5)->no1)
pub const SREMK2       (((volatile __near __bitf_T *)0xFFE5)->no2)
pub const DMAMK0       (((volatile __near __bitf_T *)0xFFE5)->no3)
pub const DMAMK1       (((volatile __near __bitf_T *)0xFFE5)->no4)
pub const CSIMK00      (((volatile __near __bitf_T *)0xFFE5)->no5)
pub const IICMK00      (((volatile __near __bitf_T *)0xFFE5)->no5)
pub const STMK0        (((volatile __near __bitf_T *)0xFFE5)->no5)
pub const CSIMK01      (((volatile __near __bitf_T *)0xFFE5)->no6)
pub const IICMK01      (((volatile __near __bitf_T *)0xFFE5)->no6)
pub const SRMK0        (((volatile __near __bitf_T *)0xFFE5)->no6)
pub const SREMK0       (((volatile __near __bitf_T *)0xFFE5)->no7)
pub const TMMK01H      (((volatile __near __bitf_T *)0xFFE5)->no7)
pub const MK1          (*(volatile __near unsigned short *)0xFFE6)
pub const MK1L         (*(volatile __near unsigned char  *)0xFFE6)
pub const MK1L_bit     (*(volatile __near __bitf_T *)0xFFE6)
pub const MK1H         (*(volatile __near unsigned char  *)0xFFE7)
pub const MK1H_bit     (*(volatile __near __bitf_T *)0xFFE7)
pub const CSIMK10      (((volatile __near __bitf_T *)0xFFE6)->no0)
pub const IICMK10      (((volatile __near __bitf_T *)0xFFE6)->no0)
pub const STMK1        (((volatile __near __bitf_T *)0xFFE6)->no0)
pub const CSIMK11      (((volatile __near __bitf_T *)0xFFE6)->no1)
pub const IICMK11      (((volatile __near __bitf_T *)0xFFE6)->no1)
pub const SRMK1        (((volatile __near __bitf_T *)0xFFE6)->no1)
pub const SREMK1       (((volatile __near __bitf_T *)0xFFE6)->no2)
pub const TMMK03H      (((volatile __near __bitf_T *)0xFFE6)->no2)
pub const IICAMK0      (((volatile __near __bitf_T *)0xFFE6)->no3)
pub const TMMK00       (((volatile __near __bitf_T *)0xFFE6)->no4)
pub const TMMK01       (((volatile __near __bitf_T *)0xFFE6)->no5)
pub const TMMK02       (((volatile __near __bitf_T *)0xFFE6)->no6)
pub const TMMK03       (((volatile __near __bitf_T *)0xFFE6)->no7)
pub const ADMK         (((volatile __near __bitf_T *)0xFFE7)->no0)
pub const RTCMK        (((volatile __near __bitf_T *)0xFFE7)->no1)
pub const ITMK         (((volatile __near __bitf_T *)0xFFE7)->no2)
pub const KRMK         (((volatile __near __bitf_T *)0xFFE7)->no3)
pub const TMMK04       (((volatile __near __bitf_T *)0xFFE7)->no7)
pub const PR00         (*(volatile __near unsigned short *)0xFFE8)
pub const PR00L        (*(volatile __near unsigned char  *)0xFFE8)
pub const PR00L_bit    (*(volatile __near __bitf_T *)0xFFE8)
pub const PR00H        (*(volatile __near unsigned char  *)0xFFE9)
pub const PR00H_bit    (*(volatile __near __bitf_T *)0xFFE9)
pub const WDTIPR0      (((volatile __near __bitf_T *)0xFFE8)->no0)
pub const LVIPR0       (((volatile __near __bitf_T *)0xFFE8)->no1)
pub const PPR00        (((volatile __near __bitf_T *)0xFFE8)->no2)
pub const PPR01        (((volatile __near __bitf_T *)0xFFE8)->no3)
pub const PPR02        (((volatile __near __bitf_T *)0xFFE8)->no4)
pub const PPR03        (((volatile __near __bitf_T *)0xFFE8)->no5)
pub const PPR04        (((volatile __near __bitf_T *)0xFFE8)->no6)
pub const PPR05        (((volatile __near __bitf_T *)0xFFE8)->no7)
pub const CSIPR020     (((volatile __near __bitf_T *)0xFFE9)->no0)
pub const IICPR020     (((volatile __near __bitf_T *)0xFFE9)->no0)
pub const STPR02       (((volatile __near __bitf_T *)0xFFE9)->no0)
pub const CSIPR021     (((volatile __near __bitf_T *)0xFFE9)->no1)
pub const IICPR021     (((volatile __near __bitf_T *)0xFFE9)->no1)
pub const SRPR02       (((volatile __near __bitf_T *)0xFFE9)->no1)
pub const SREPR02      (((volatile __near __bitf_T *)0xFFE9)->no2)
pub const DMAPR00      (((volatile __near __bitf_T *)0xFFE9)->no3)
pub const DMAPR01      (((volatile __near __bitf_T *)0xFFE9)->no4)
pub const CSIPR000     (((volatile __near __bitf_T *)0xFFE9)->no5)
pub const IICPR000     (((volatile __near __bitf_T *)0xFFE9)->no5)
pub const STPR00       (((volatile __near __bitf_T *)0xFFE9)->no5)
pub const CSIPR001     (((volatile __near __bitf_T *)0xFFE9)->no6)
pub const IICPR001     (((volatile __near __bitf_T *)0xFFE9)->no6)
pub const SRPR00       (((volatile __near __bitf_T *)0xFFE9)->no6)
pub const SREPR00      (((volatile __near __bitf_T *)0xFFE9)->no7)
pub const TMPR001H     (((volatile __near __bitf_T *)0xFFE9)->no7)
pub const PR01         (*(volatile __near unsigned short *)0xFFEA)
pub const PR01L        (*(volatile __near unsigned char  *)0xFFEA)
pub const PR01L_bit    (*(volatile __near __bitf_T *)0xFFEA)
pub const PR01H        (*(volatile __near unsigned char  *)0xFFEB)
pub const PR01H_bit    (*(volatile __near __bitf_T *)0xFFEB)
pub const CSIPR010     (((volatile __near __bitf_T *)0xFFEA)->no0)
pub const IICPR010     (((volatile __near __bitf_T *)0xFFEA)->no0)
pub const STPR01       (((volatile __near __bitf_T *)0xFFEA)->no0)
pub const CSIPR011     (((volatile __near __bitf_T *)0xFFEA)->no1)
pub const IICPR011     (((volatile __near __bitf_T *)0xFFEA)->no1)
pub const SRPR01       (((volatile __near __bitf_T *)0xFFEA)->no1)
pub const SREPR01      (((volatile __near __bitf_T *)0xFFEA)->no2)
pub const TMPR003H     (((volatile __near __bitf_T *)0xFFEA)->no2)
pub const IICAPR00     (((volatile __near __bitf_T *)0xFFEA)->no3)
pub const TMPR000      (((volatile __near __bitf_T *)0xFFEA)->no4)
pub const TMPR001      (((volatile __near __bitf_T *)0xFFEA)->no5)
pub const TMPR002      (((volatile __near __bitf_T *)0xFFEA)->no6)
pub const TMPR003      (((volatile __near __bitf_T *)0xFFEA)->no7)
pub const ADPR0        (((volatile __near __bitf_T *)0xFFEB)->no0)
pub const RTCPR0       (((volatile __near __bitf_T *)0xFFEB)->no1)
pub const ITPR0        (((volatile __near __bitf_T *)0xFFEB)->no2)
pub const KRPR0        (((volatile __near __bitf_T *)0xFFEB)->no3)
pub const TMPR004      (((volatile __near __bitf_T *)0xFFEB)->no7)
pub const PR10         (*(volatile __near unsigned short *)0xFFEC)
pub const PR10L        (*(volatile __near unsigned char  *)0xFFEC)
pub const PR10L_bit    (*(volatile __near __bitf_T *)0xFFEC)
pub const PR10H        (*(volatile __near unsigned char  *)0xFFED)
pub const PR10H_bit    (*(volatile __near __bitf_T *)0xFFED)
pub const WDTIPR1      (((volatile __near __bitf_T *)0xFFEC)->no0)
pub const LVIPR1       (((volatile __near __bitf_T *)0xFFEC)->no1)
pub const PPR10        (((volatile __near __bitf_T *)0xFFEC)->no2)
pub const PPR11        (((volatile __near __bitf_T *)0xFFEC)->no3)
pub const PPR12        (((volatile __near __bitf_T *)0xFFEC)->no4)
pub const PPR13        (((volatile __near __bitf_T *)0xFFEC)->no5)
pub const PPR14        (((volatile __near __bitf_T *)0xFFEC)->no6)
pub const PPR15        (((volatile __near __bitf_T *)0xFFEC)->no7)
pub const CSIPR120     (((volatile __near __bitf_T *)0xFFED)->no0)
pub const IICPR120     (((volatile __near __bitf_T *)0xFFED)->no0)
pub const STPR12       (((volatile __near __bitf_T *)0xFFED)->no0)
pub const CSIPR121     (((volatile __near __bitf_T *)0xFFED)->no1)
pub const IICPR121     (((volatile __near __bitf_T *)0xFFED)->no1)
pub const SRPR12       (((volatile __near __bitf_T *)0xFFED)->no1)
pub const SREPR12      (((volatile __near __bitf_T *)0xFFED)->no2)
pub const DMAPR10      (((volatile __near __bitf_T *)0xFFED)->no3)
pub const DMAPR11      (((volatile __near __bitf_T *)0xFFED)->no4)
pub const CSIPR100     (((volatile __near __bitf_T *)0xFFED)->no5)
pub const IICPR100     (((volatile __near __bitf_T *)0xFFED)->no5)
pub const STPR10       (((volatile __near __bitf_T *)0xFFED)->no5)
pub const CSIPR101     (((volatile __near __bitf_T *)0xFFED)->no6)
pub const IICPR101     (((volatile __near __bitf_T *)0xFFED)->no6)
pub const SRPR10       (((volatile __near __bitf_T *)0xFFED)->no6)
pub const SREPR10      (((volatile __near __bitf_T *)0xFFED)->no7)
pub const TMPR101H     (((volatile __near __bitf_T *)0xFFED)->no7)
pub const PR11         (*(volatile __near unsigned short *)0xFFEE)
pub const PR11L        (*(volatile __near unsigned char  *)0xFFEE)
pub const PR11L_bit    (*(volatile __near __bitf_T *)0xFFEE)
pub const PR11H        (*(volatile __near unsigned char  *)0xFFEF)
pub const PR11H_bit    (*(volatile __near __bitf_T *)0xFFEF)
pub const CSIPR110     (((volatile __near __bitf_T *)0xFFEE)->no0)
pub const IICPR110     (((volatile __near __bitf_T *)0xFFEE)->no0)
pub const STPR11       (((volatile __near __bitf_T *)0xFFEE)->no0)
pub const CSIPR111     (((volatile __near __bitf_T *)0xFFEE)->no1)
pub const IICPR111     (((volatile __near __bitf_T *)0xFFEE)->no1)
pub const SRPR11       (((volatile __near __bitf_T *)0xFFEE)->no1)
pub const SREPR11      (((volatile __near __bitf_T *)0xFFEE)->no2)
pub const TMPR103H     (((volatile __near __bitf_T *)0xFFEE)->no2)
pub const IICAPR10     (((volatile __near __bitf_T *)0xFFEE)->no3)
pub const TMPR100      (((volatile __near __bitf_T *)0xFFEE)->no4)
pub const TMPR101      (((volatile __near __bitf_T *)0xFFEE)->no5)
pub const TMPR102      (((volatile __near __bitf_T *)0xFFEE)->no6)
pub const TMPR103      (((volatile __near __bitf_T *)0xFFEE)->no7)
pub const ADPR1        (((volatile __near __bitf_T *)0xFFEF)->no0)
pub const RTCPR1       (((volatile __near __bitf_T *)0xFFEF)->no1)
pub const ITPR1        (((volatile __near __bitf_T *)0xFFEF)->no2)
pub const KRPR1        (((volatile __near __bitf_T *)0xFFEF)->no3)
pub const TMPR104      (((volatile __near __bitf_T *)0xFFEF)->no7)
pub const MDAL         (*(volatile __near unsigned short *)0xFFF0)
pub const MULA         (*(volatile __near unsigned short *)0xFFF0)
pub const MDAH         (*(volatile __near unsigned short *)0xFFF2)
pub const MULB         (*(volatile __near unsigned short *)0xFFF2)
pub const MDBH         (*(volatile __near unsigned short *)0xFFF4)
pub const MULOH        (*(volatile __near unsigned short *)0xFFF4)
pub const MDBL         (*(volatile __near unsigned short *)0xFFF6)
pub const MULOL        (*(volatile __near unsigned short *)0xFFF6)
pub const PMC          (*(volatile __near unsigned char  *)0xFFFE)
pub const PMC_bit      (*(volatile __near __bitf_T *)0xFFFE)
pub const MAA          (((volatile __near __bitf_T *)0xFFFE)->no0)
*/

mod cty {
pub type int8_t = i8;
pub type int16_t = i16;
pub type int32_t = i32;
pub type int64_t = i64;

pub type uint8_t = u8;
pub type uint16_t = u16;
pub type uint32_t = u32;
pub type uint64_t = u64;

pub type c_char = i8;
pub type c_schar = i8;
pub type c_short = i16;
pub type c_longlong = i64;

pub type c_uchar = u8;
pub type c_ushort = u16;
pub type c_ulonglong = u64;

pub type c_int = i32;
pub type c_uint = u32;
pub type c_long = i32;
pub type c_ulong = u32;

pub type c_float = f32;
pub type c_double = f64;

pub type intmax_t = i64;
pub type uintmax_t = u64;

pub type size_t = usize;
pub type ptrdiff_t = isize;
pub type intptr_t = isize;
pub type uintptr_t = usize;
pub type ssize_t = isize;

pub type c_void = core::ffi::c_void;
}

// rust-binding codes
// include!("bindings.rs");
// include!("g13_port.rs");
// ng : cty 
// mod bindings;
// mod g13_port;
include!("iodefine.rs");
// include!("iodefine_ext.rs");

